import type { ConceptLesson } from './concepts';

// Readings in `romaji` are shown under each example. Quiz = one quick check per lesson.

export const n5Lessons: ConceptLesson[] = [
  {
    id: 'n5-greetings',
    title: 'Mga pagbati (greetings)',
    pattern: 'おはようございます / こんにちは / ありがとう',
    summary: 'Ang mga salitang gagamitin mo araw-araw.',
    body: [
      `Sa Japanese, may iba't ibang pagbati depende sa oras ng araw. おはようございます ang "magandang umaga", こんにちは ang "magandang tanghali/hapon", at こんばんは ang "magandang gabi".`,
      `Para sa "salamat", ありがとうございます ang magalang na bersyon. Sa kaibigan, puwede ang ありがとう lang. Ang すみません ay "excuse me" at "pasensya na" din, kaya sobrang gamit.`,
      `Bago kumain, sasabihin ang いただきます (parang pasasalamat bago kumain), at pagkatapos, ごちそうさまでした. Walang eksaktong Tagalog, pero parang "Salamat sa pagkain".`,
    ],
    examples: [
      { jp: `おはようございます`, romaji: `ohayou gozaimasu`, meaning: `Magandang umaga` },
      { jp: `ありがとうございます`, romaji: `arigatou gozaimasu`, meaning: `Maraming salamat` },
      { jp: `すみません`, romaji: `sumimasen`, meaning: `Excuse me / Pasensya na` },
      { jp: `いただきます`, romaji: `itadakimasu`, meaning: `Bago kumain` },
    ],
    remember: `ございます ang nagpapa-"po" sa pagbati. Idagdag mo ito kapag mas nakatatanda ang kausap.`,
    tip: `Sa kaibigan, tanggalin ang ございます: おはよう, ありがとう. Sa boss o matanda, laging buo.`,
    check: { q: `Ano ang sinasabi bago kumain?`, options: [`ごちそうさま`, `いただきます`, `こんばんは`, `すみません`], answer: 1 },
  },
  {
    id: 'n5-desu',
    title: 'です: "ay" sa Japanese',
    pattern: 'A は B です',
    summary: 'Ang pinakapayak na pangungusap.',
    body: [
      `Ang です ang katumbas ng "ay" o "ako ay". Pormula: A は B です, "Si A ay si B". Ang は dito ay binibigkas na "wa", ito ang topic marker, parang "Tungkol sa A...".`,
      `Para gawing tanong, idagdag lang ang か sa dulo: あなたは がくせいですか。(Estudyante ka ba?) Walang tandang pananong na kailangan, pero puwede.`,
      `Para sa "hindi", palitan ang です ng じゃありません (o ではありません sa mas pormal): わたしは せんせいじゃありません。`,
    ],
    examples: [
      { jp: `わたしは マリアです。`, romaji: `watashi wa maria desu`, meaning: `Ako si Maria.` },
      { jp: `ジョンさんは がくせいですか。`, romaji: `jon-san wa gakusei desu ka`, meaning: `Estudyante ba si John?` },
      { jp: `いいえ、せんせいじゃありません。`, romaji: `iie, sensei ja arimasen`, meaning: `Hindi, hindi po ako guro.` },
    ],
    remember: `は = "wa" (topic). です = "ay". か = tanong. じゃありません = hindi.`,
    tip: `Huwag magdagdag ng さん sa sarili mong pangalan. Ang さん ay para sa ibang tao lamang (parang "Mr./Ms.").`,
    check: { q: `Paano sasabihin ang "Hindi ako estudyante"?`, options: [`がくせいですか`, `がくせいです`, `がくせいじゃありません`, `がくせいは`], answer: 2 },
  },
  {
    id: 'n5-kosoado',
    title: 'これ・それ・あれ (ito, iyan, iyon)',
    pattern: 'これ / それ / あれ / どれ',
    summary: 'Pagturo ng bagay ayon sa layo.',
    body: [
      `Parang Tagalog na "ito, iyan, iyon". これ = malapit sa nagsasalita, それ = malapit sa kausap, あれ = malayo sa pareho, どれ = alin.`,
      `Kapag may kasunod na pangngalan, gamitin ang この, その, あの, どの: この ほん (aklat na ito). Hindi puwedeng mag-isa ang この, laging may pangngalan.`,
      `Para sa lugar: ここ (dito), そこ (diyan), あそこ (doon), どこ (saan). Pareho ang pattern na ko-so-a-do.`,
    ],
    examples: [
      { jp: `これは ほんです。`, romaji: `kore wa hon desu`, meaning: `Ito ay aklat.` },
      { jp: `あれは なんですか。`, romaji: `are wa nan desu ka`, meaning: `Ano iyon?` },
      { jp: `この かばんは わたしのです。`, romaji: `kono kaban wa watashi no desu`, meaning: `Akin ang bag na ito.` },
    ],
    remember: `Ko = malapit sa akin. So = malapit sa iyo. A = malayo sa atin. Do = alin?`,
    tip: `Sa telepono o kuwento, ang その ay madalas gamitin para sa bagay na nabanggit na ng kausap.`,
    check: { q: `Ano ang "iyon" (malayo sa pareho)?`, options: [`これ`, `それ`, `あれ`, `どれ`], answer: 2 },
  },
  {
    id: 'n5-numbers',
    title: 'Mga numero 1 hanggang 10',
    pattern: 'いち、に、さん、し/よん…',
    summary: 'Magbilang at gamitin sa presyo at edad.',
    body: [
      `1 いち, 2 に, 3 さん, 4 よん (o し), 5 ご, 6 ろく, 7 なな (o しち), 8 はち, 9 きゅう (o く), 10 じゅう. May dalawang basa ang 4, 7, at 9, pero よん, なな, きゅう ang pinakakaraniwan.`,
      `Para sa 11 hanggang 19, sabihin ang じゅう + numero: 11 = じゅういち. Ang 20 = にじゅう, 30 = さんじゅう. Napakaayos ng sistema.`,
      `Ang 100 ay ひゃく, 1,000 ay せん, at 10,000 ay いちまん. Ang Japanese ay nagbibilang bawat 10,000 (man), hindi bawat 1,000 tulad natin.`,
    ],
    examples: [
      { jp: `じゅうに`, romaji: `juu ni`, meaning: `12` },
      { jp: `にじゅうご`, romaji: `nijuu go`, meaning: `25` },
      { jp: `ひゃくえん`, romaji: `hyaku en`, meaning: `100 yen` },
    ],
    remember: `Pormula: sampuan + isahan. 25 = 2-10-5 = にじゅうご.`,
    tip: `Iwasan ang し sa 4 at 7 dahil kapareho ito ng 死 (kamatayan). Kaya よん at なな ang gamit.`,
    check: { q: `Ano ang 30?`, options: [`じゅうさん`, `さんじゅう`, `さんひゃく`, `さんまん`], answer: 1 },
  },
  {
    id: 'n5-no',
    title: 'の: pag-aari at paglalarawan',
    pattern: 'A の B',
    summary: 'Ang "ng" ng Japanese.',
    body: [
      `の ang nag-uugnay ng dalawang pangngalan, parang "ng" sa Tagalog. わたしの ほん = aklat ko. Pero baliktad ang ayos: sa Tagalog "aklat ko", sa Japanese "ko-ng aklat".`,
      `Hindi lang pag-aari ang gamit. にほんの くるま = kotseng Hapon. にほんごの せんせい = guro ng Japanese.`,
      `Puwede ring tanggalin ang pangalawang pangngalan kapag halata na: この ほんは わたしのです = akin iyan (aklat ko).`,
    ],
    examples: [
      { jp: `わたしの ともだち`, romaji: `watashi no tomodachi`, meaning: `kaibigan ko` },
      { jp: `にほんごの ほん`, romaji: `nihongo no hon`, meaning: `aklat ng Japanese` },
      { jp: `これは せんせいの かさです。`, romaji: `kore wa sensei no kasa desu`, meaning: `Payong ito ng guro.` },
    ],
    remember: `A の B = "B ng A". Ang may-ari ay laging nauuna.`,
    tip: `Baliktarin ang Tagalog sa isip mo: "bahay ng kaibigan ko" → "watashi no tomodachi no ie".`,
    check: { q: `Ano ang "aklat ng guro"?`, options: [`ほんの せんせい`, `せんせいの ほん`, `せんせいは ほん`, `ほんが せんせい`], answer: 1 },
  },
  {
    id: 'n5-masu-wo',
    title: 'Pandiwa na ます at particle を',
    pattern: 'N を V ます',
    summary: 'Ang pandiwa ay laging nasa dulo.',
    body: [
      `Ang pandiwa sa magalang na anyo ay nagtatapos sa ます. たべます (kumakain/kakain), のみます (umiinom), みます (nanonood/tumitingin). Isang anyo lang para sa kasalukuyan at hinaharap, nasa konteksto ang pagkakaiba.`,
      `Ang を ay marka ng object, ang tinatamaan ng kilos: みずを のみます = umiinom ng tubig. Binibigkas na "o".`,
      `Negatibo: ません. たべません = hindi kumakain. Tanong: ますか. たべますか = kumakain ka ba?`,
    ],
    examples: [
      { jp: `ごはんを たべます。`, romaji: `gohan o tabemasu`, meaning: `Kumakain ako ng kanin.` },
      { jp: `テレビを みません。`, romaji: `terebi o mimasen`, meaning: `Hindi ako nanonood ng TV.` },
      { jp: `コーヒーを のみますか。`, romaji: `koohii o nomimasu ka`, meaning: `Iinom ka ba ng kape?` },
    ],
    remember: `Ayos: Object を Verb. ます = oo, ません = hindi, ますか = tanong.`,
    tip: `Hindi nagbabago ang pandiwa para sa tao (ako, ikaw, siya). Isang anyo lang, malaking ginhawa.`,
    check: { q: `Ano ang "hindi kumakain"?`, options: [`たべます`, `たべません`, `たべました`, `たべますか`], answer: 1 },
  },
  {
    id: 'n5-ni-de-e',
    title: 'に, で, へ: lugar at direksyon',
    pattern: 'に / で / へ',
    summary: 'Tatlong particle na madalas pagkalitohan.',
    body: [
      `に ay para sa destinasyon, oras, at lugar ng pag-iral: がっこうに いきます (pupunta sa school), 7じに おきます (gumigising nang 7).`,
      `で ay para sa lugar kung saan ginagawa ang kilos: カフェで べんきょうします (nag-aaral sa cafe). Maaari rin itong "gamit ang": バスで いきます (sumasakay ng bus).`,
      `へ ay "papunta sa" (binibigkas na "e"). Halos kapareho ng に pagdating sa destinasyon, pero に ang mas karaniwan sa pagsasalita.`,
    ],
    examples: [
      { jp: `がっこうへ いきます。`, romaji: `gakkou e ikimasu`, meaning: `Pupunta ako sa school.` },
      { jp: `としょかんで ほんを よみます。`, romaji: `toshokan de hon o yomimasu`, meaning: `Nagbabasa ako ng aklat sa library.` },
      { jp: `ごじに かえります。`, romaji: `goji ni kaerimasu`, meaning: `Uuwi ako nang alas-5.` },
    ],
    remember: `に = papunta / oras / "nasa". で = kung saan ginagawa. Tanong: "may galaw ba sa loob ng lugar?" Kung oo, で.`,
    tip: `Mabilis na test: kung ang pandiwa ay "pumunta/dumating/umuwi", に o へ. Kung kilos na ginagawa (kumain, mag-aral), で.`,
    check: { q: `"Kumakain ako sa restaurant": alin ang tama?`, options: [`レストランに たべます`, `レストランで たべます`, `レストランを たべます`, `レストランの たべます`], answer: 1 },
  },
  {
    id: 'n5-time',
    title: 'Oras at araw',
    pattern: '〜じ / 〜ふん / 〜に',
    summary: 'Magsabi ng oras at kailan.',
    body: [
      `Ang oras ay numero + じ: 1じ いちじ, 2じ にじ. Pero 4じ ay よじ, 7じ ay しちじ, 9じ ay くじ (ito ang mga eksepsiyon).`,
      `Minuto: numero + ふん/ぷん: 5ふん ごふん, 10ぷん じゅっぷん. Ang half ay はん: 3じはん = 3:30.`,
      `Gamitin ang に pagkatapos ng eksaktong oras: 7じに おきます. Pero hindi kailangan ang に sa "ngayon", "bukas", at "kahapon" (きょう, あした, きのう).`,
    ],
    examples: [
      { jp: `いま ごじです。`, romaji: `ima goji desu`, meaning: `Alas-5 na ngayon.` },
      { jp: `あしたは くじに いきます。`, romaji: `ashita wa kuji ni ikimasu`, meaning: `Bukas, pupunta ako nang alas-9.` },
      { jp: `ごご さんじはんです。`, romaji: `gogo sanji han desu`, meaning: `Alas-3:30 ng hapon.` },
    ],
    remember: `よじ, しちじ, くじ ay espesyal. ごぜん = AM, ごご = PM.`,
    tip: `Idikit ang に sa eksaktong oras (7じに), pero hindi sa relatibong salita (あした, きょう).`,
    check: { q: `Ano ang "4 o'clock"?`, options: [`しじ`, `よんじ`, `よじ`, `よっじ`], answer: 2 },
  },
  {
    id: 'n5-adjectives',
    title: 'Pang-uri: い at な',
    pattern: 'A-い / A-な + N',
    summary: 'Dalawang uri ng adjective.',
    body: [
      `Ang i-adjective ay nagtatapos sa い: おいしい (masarap), たかい (mahal/mataas). Puwede itong direktang ilagay bago ang pangngalan: おいしい りょうり.`,
      `Ang na-adjective ay kailangan ng な bago ang pangngalan: きれいな へや (malinis na kuwarto), しずかな まち (tahimik na bayan). Sa dulo ng pangungusap, です lang: へやは きれいです。`,
      `Negatibo ng い: palitan ang い ng くない. おいしくない = hindi masarap. Ang na-adjective: じゃありません. きれいじゃありません.`,
    ],
    examples: [
      { jp: `この ラーメンは おいしいです。`, romaji: `kono raamen wa oishii desu`, meaning: `Masarap ang ramen na ito.` },
      { jp: `ここは しずかな まちです。`, romaji: `koko wa shizuka na machi desu`, meaning: `Tahimik na bayan ito.` },
      { jp: `きょうは あつくないです。`, romaji: `kyou wa atsukunai desu`, meaning: `Hindi mainit ngayon.` },
    ],
    remember: `い-adj: bago ang noun, walang dagdag. な-adj: kailangan ng な. Negatibo ng い-adj: くない.`,
    tip: `Espesyal ang いい (mabuti): negatibo nito ay よくない, hindi いくない.`,
    check: { q: `Negatibo ng たかい?`, options: [`たかいじゃありません`, `たかくない`, `たかなくない`, `たからない`], answer: 1 },
  },
  {
    id: 'n5-aru-iru',
    title: 'あります・います: "may" at "nandito"',
    pattern: 'N が あります / います',
    summary: 'Pag-iral ng bagay at ng nabubuhay.',
    body: [
      `Dalawang pandiwa ang katumbas ng "may" o "nandito": あります para sa walang buhay (mesa, libro, ideya), at います para sa may buhay (tao, hayop).`,
      `Pormula: Lugar に Bagay が あります. つくえの うえに ほんが あります = May aklat sa ibabaw ng mesa.`,
      `Para sa lokasyon ng isang kilalang bagay: Bagay は Lugar に あります. トイレは あそこに あります = Nandoon ang CR.`,
    ],
    examples: [
      { jp: `へやに ねこが います。`, romaji: `heya ni neko ga imasu`, meaning: `May pusa sa kuwarto.` },
      { jp: `つくえの うえに ほんが あります。`, romaji: `tsukue no ue ni hon ga arimasu`, meaning: `May aklat sa mesa.` },
      { jp: `えきは どこに ありますか。`, romaji: `eki wa doko ni arimasu ka`, meaning: `Nasaan ang istasyon?` },
    ],
    remember: `Buhay = います. Hindi buhay = あります. Ang bagay ay may が, ang lugar ay may に.`,
    tip: `Ang halaman ay あります (hindi gumagalaw sa pananaw ng grammar), at ang robot ay あります din.`,
    check: { q: `"May pusa" gamit ang aling pandiwa?`, options: [`あります`, `います`, `です`, `します`], answer: 1 },
  },
  {
    id: 'n5-past',
    title: 'Nakaraan: ました・でした',
    pattern: 'V ました / N でした',
    summary: 'Ang nangyari na.',
    body: [
      `Para sa pandiwa, palitan ang ます ng ました: たべます → たべました (kumain). Negatibo: ませんでした (hindi kumain).`,
      `Para sa です, gamitin ang でした: きのうは あめでした (umulan kahapon). Negatibo: じゃありませんでした.`,
      `Para sa い-adjective, palitan ang い ng かったです: たのしい → たのしかったです (masaya noon). Para sa な-adjective, でした: しずかでした.`,
    ],
    examples: [
      { jp: `きのう えいがを みました。`, romaji: `kinou eiga o mimashita`, meaning: `Nanood ako ng pelikula kahapon.` },
      { jp: `パーティーは たのしかったです。`, romaji: `paatii wa tanoshikatta desu`, meaning: `Masaya ang party.` },
      { jp: `ごはんを たべませんでした。`, romaji: `gohan o tabemasen deshita`, meaning: `Hindi ako kumain.` },
    ],
    remember: `ます → ました, ません → ませんでした, です → でした, い → かったです.`,
    tip: `Isipin: lahat ng nakaraan ay may "ta" tunog sa dulo: mashita, deshita, katta.`,
    check: { q: `Ano ang nakaraan ng のみます?`, options: [`のみません`, `のみました`, `のんでした`, `のみます`], answer: 1 },
  },
  {
    id: 'n5-te-kudasai',
    title: 'て-form at 〜てください',
    pattern: 'V て + ください',
    summary: 'Humiling nang magalang.',
    body: [
      `Ang て-form ay isa sa pinakamahalagang anyo sa Japanese. Ginagamit ito para humiling, mag-ugnay ng kilos, at marami pa. Idagdag ang ください para sa "pakiusap".`,
      `Mga patakaran (Group 1 verbs): う/つ/る → って (かう→かって), む/ぶ/ぬ → んで (のむ→のんで), く → いて (かく→かいて), ぐ → いで, す → して. Ang iku ay espesyal: いって.`,
      `Group 2 (ru-verbs): tanggalin ang る, idagdag ang て: たべる → たべて. Ang する → して, くる → きて.`,
    ],
    examples: [
      { jp: `ちょっと まってください。`, romaji: `chotto matte kudasai`, meaning: `Pakihintay sandali.` },
      { jp: `ここに なまえを かいてください。`, romaji: `koko ni namae o kaite kudasai`, meaning: `Pakisulat ang pangalan dito.` },
      { jp: `もういちど いってください。`, romaji: `mou ichido itte kudasai`, meaning: `Pakisabi ulit.` },
    ],
    remember: `Group 1: う/つ/る→って. む/ぶ/ぬ→んで. く→いて. す→して. Group 2: -る→-て.`,
    tip: `Kantahin ang pattern habang nagsasanay. "って, んで, いて, して" ay tumatatak sa bibig kapag inulit.`,
    check: { q: `て-form ng のむ?`, options: [`のって`, `のんで`, `のみて`, `のいて`], answer: 1 },
  },
  {
    id: 'n5-tai-suki',
    title: '〜たいです at すき',
    pattern: 'V ます-stem + たい / N が すき',
    summary: 'Magsabi ng gusto mo.',
    body: [
      `Para sa "gusto kong gawin", tanggalin ang ます at idagdag ang たい: たべます → たべたい. Ito ay parang い-adjective, kaya negatibo ang たくない at nakaraan ang たかった.`,
      `Ang object ay puwedeng を o が: すしを たべたいです o すしが たべたいです. Pareho lang.`,
      `Para sa "gusto ko ang ___" gamitin ang N が すき(です): ねこが すきです. Kabaligtaran: きらい. Pansinin: が, hindi を.`,
    ],
    examples: [
      { jp: `にほんへ いきたいです。`, romaji: `nihon e ikitai desu`, meaning: `Gusto kong pumunta sa Japan.` },
      { jp: `ラーメンが すきです。`, romaji: `raamen ga suki desu`, meaning: `Gusto ko ang ramen.` },
      { jp: `なにも たべたくないです。`, romaji: `nani mo tabetakunai desu`, meaning: `Wala akong gustong kainin.` },
    ],
    remember: `V-ます→たい (gusto). N が すき (gusto ang N). Hindi を sa すき.`,
    tip: `Sa pagsasalita tungkol sa ibang tao, iwasan ang たい. Gamitin ang たがっています, dahil hindi mo alam ang loob ng iba.`,
    check: { q: `"Gusto ko ang pusa":`, options: [`ねこを すきです`, `ねこが すきです`, `ねこに すきです`, `ねこで すきです`], answer: 1 },
  },
];

export const n4Lessons: ConceptLesson[] = [
  {
    id: 'n4-teiru',
    title: '〜ている: kasalukuyang ginagawa',
    pattern: 'V て + いる',
    summary: 'Ginagawa ngayon at patuloy na kalagayan.',
    body: [
      `て-form + いる ay "ginagawa ngayon" (progressive): いま たべています = kumakain ako ngayon. Parang "-ing" sa English o "nag-" sa Tagalog.`,
      `Para sa mga pandiwa ng pagbabago, ito ay "resulta ng nangyari": けっこんしています = kasal (nagpakasal at ganun pa rin). すんでいます = nakatira.`,
      `Sa casual, nawawala ang い: たべてる, みてる. Madalas mo itong maririnig sa anime.`,
    ],
    examples: [
      { jp: `いま ごはんを たべています。`, romaji: `ima gohan o tabete imasu`, meaning: `Kumakain ako ngayon.` },
      { jp: `マニラに すんでいます。`, romaji: `manira ni sunde imasu`, meaning: `Nakatira ako sa Maynila.` },
      { jp: `もう けっこんしています。`, romaji: `mou kekkon shite imasu`, meaning: `Kasal na siya.` },
    ],
    remember: `〜ている = ginagawa ngayon o kasalukuyang kalagayan.`,
    tip: `Ang "nakatira" at "kasal" ay laging ている. Hindi sinasabing すみます kapag sinasabi kung saan ka nakatira.`,
    check: { q: `"Nakatira ako sa Cebu":`, options: [`セブに すみます`, `セブに すんでいます`, `セブで すみました`, `セブを すんでいます`], answer: 1 },
  },
  {
    id: 'n4-nai-form',
    title: 'ない-form: negatibo',
    pattern: 'V ない / V ないでください',
    summary: 'Casual na negatibo at "huwag".',
    body: [
      `Ang ない-form ay casual na negatibo. Group 1: palitan ang huling う-sound ng あ-sound + ない: かく → かかない, のむ → のまない. (Espesyal: かう → かわない.)`,
      `Group 2: tanggalin ang る, idagdag ang ない: たべる → たべない. する → しない, くる → こない.`,
      `Para sa "huwag mong...", idagdag ang ないでください: ここで たばこを すわないでください (huwag manigarilyo dito).`,
    ],
    examples: [
      { jp: `きょうは がっこうへ いかない。`, romaji: `kyou wa gakkou e ikanai`, meaning: `Hindi ako pupunta sa school ngayon.` },
      { jp: `さかなを たべない。`, romaji: `sakana o tabenai`, meaning: `Hindi ako kumakain ng isda.` },
      { jp: `ここで はしらないでください。`, romaji: `koko de hashiranaide kudasai`, meaning: `Huwag tumakbo dito, pakiusap.` },
    ],
    remember: `Group 1: u→a + ない. Group 2: -る→ない. ないでください = huwag.`,
    tip: `Mas magiliw ang ないでください kaysa sa pag-utos. Sa karatula, makikita mo ito palagi.`,
    check: { q: `ない-form ng のむ?`, options: [`のみない`, `のまない`, `のんない`, `のむない`], answer: 1 },
  },
  {
    id: 'n4-potential',
    title: 'Kakayahan: できる at potential form',
    pattern: 'V-る + ことができる / V potential',
    summary: 'Magsabi ng "kaya kong...".',
    body: [
      `Dalawang paraan: (1) V-る + ことが できる, (2) potential form. Ang ことが できる ay mas pormal at tuwiran: にほんごを はなすことが できます = kaya kong magsalita ng Japanese.`,
      `Ang potential form ay ginagawang isang bagong pandiwa: Group 1 palitan ang u → e + る (かく → かける), Group 2: -る → -られる (たべる → たべられる). する → できる, くる → こられる.`,
      `Karaniwan ang object ay nagiging が: にほんごが はなせます (kaya kong magsalita ng Japanese).`,
    ],
    examples: [
      { jp: `ひらがなが よめます。`, romaji: `hiragana ga yomemasu`, meaning: `Nakakabasa ako ng hiragana.` },
      { jp: `およぐことが できます。`, romaji: `oyogu koto ga dekimasu`, meaning: `Marunong akong lumangoy.` },
      { jp: `さしみは たべられません。`, romaji: `sashimi wa taberaremasen`, meaning: `Hindi ako makakain ng sashimi.` },
    ],
    remember: `Group 1: u→e+る. Group 2: る→られる. Object ay が.`,
    tip: `Ang 見える (nakikita) at 聞こえる (naririnig) ay hiwalay na pandiwa para sa kusang nakikita o naririnig.`,
    check: { q: `Potential ng たべる?`, options: [`たべれる`, `たべられる`, `たべせる`, `たべえる`], answer: 1 },
  },
  {
    id: 'n4-koto-ga-aru',
    title: '〜たことがある: karanasan',
    pattern: 'V た + ことがある',
    summary: 'Naranasan mo na ba?',
    body: [
      `V-ta form + ことが ある ay "nakagawa na ako ng ___ kahit isang beses". Parang "nakapunta na ako sa Japan" sa Tagalog.`,
      `Gumawa ng ta-form: ito ay pareho ng て-form pero て→た, で→だ. たべて → たべた, よんで → よんだ.`,
      `Para sa "hindi pa", ang ことが ない: にほんへ いったことが ありません (hindi pa ako nakapunta sa Japan).`,
    ],
    examples: [
      { jp: `すしを たべたことが あります。`, romaji: `sushi o tabeta koto ga arimasu`, meaning: `Nakakain na ako ng sushi.` },
      { jp: `ふじさんに のぼったことが ありますか。`, romaji: `fujisan ni nobotta koto ga arimasu ka`, meaning: `Naakyat mo na ba ang Mt. Fuji?` },
      { jp: `ひこうきに のったことが ありません。`, romaji: `hikouki ni notta koto ga arimasen`, meaning: `Hindi pa ako nakasakay ng eroplano.` },
    ],
    remember: `Ta-form + ことがある = "nakagawa na". ことがない = "hindi pa".`,
    tip: `Hindi ito para sa kahapon lang. Ito ay para sa karanasan sa buong buhay mo.`,
    check: { q: `"Nakapunta na ako sa Japan":`, options: [`にほんへ いくことが あります`, `にほんへ いったことが あります`, `にほんへ いきたいです`, `にほんへ いきました`], answer: 1 },
  },
  {
    id: 'n4-temo-ii',
    title: '〜てもいい・〜てはいけない: pahintulot',
    pattern: 'V て + もいい / はいけない',
    summary: 'Puwede ba? Bawal.',
    body: [
      `V-て + もいいです ay "puwede". Para magtanong ng pahintulot: ここで しゃしんを とってもいいですか (puwede bang kumuha ng litrato dito?).`,
      `Para sa "bawal", V-て + はいけません. ここで たばこを すってはいけません. Mas malakas ito, madalas nasa karatula o batas.`,
      `Mas banayad na "ayoko ng ganito" ay 〜ないでください. May lakas na ranggo: ないでください (pakiusap) < てはいけません (bawal).`,
    ],
    examples: [
      { jp: `ここに すわってもいいですか。`, romaji: `koko ni suwatte mo ii desu ka`, meaning: `Puwede ba akong umupo dito?` },
      { jp: `ここで なまものを たべてはいけません。`, romaji: `koko de namamono o tabete wa ikemasen`, meaning: `Bawal kumain ng hilaw dito.` },
      { jp: `ええ、いいですよ。`, romaji: `ee, ii desu yo`, meaning: `Oo, puwede.` },
    ],
    remember: `〜てもいい = puwede. 〜てはいけない = bawal.`,
    tip: `Kapag hihingi ng pahintulot, laging idagdag ang か para maging tanong.`,
    check: { q: `"Bawal manigarilyo dito":`, options: [`すってもいい`, `すってはいけません`, `すいたいです`, `すいません`], answer: 1 },
  },
  {
    id: 'n4-volitional',
    title: '〜ましょう・〜よう: tayo na',
    pattern: 'V ましょう / V よう',
    summary: 'Mag-anyaya at magpasya.',
    body: [
      `ましょう ay "tayo na" o "gawin natin". いっしょに たべましょう = kumain tayo nang sama-sama. ましょうか ay "gagawin ko ba?" o "gagawin ba natin?"`,
      `Ang casual na bersyon ay volitional form: Group 2: -る → -よう (たべよう). Group 1: u → o + う (いく → いこう).`,
      `Sa pagpapahayag ng plano: V-よう + と おもっています ay "iniisip kong gawin". にほんへ いこうと おもっています.`,
    ],
    examples: [
      { jp: `いっしょに ひるごはんを たべましょう。`, romaji: `issho ni hirugohan o tabemashou`, meaning: `Mag-lunch tayo nang sabay.` },
      { jp: `てつだいましょうか。`, romaji: `tetsudaimashou ka`, meaning: `Tutulungan ba kita?` },
      { jp: `あした いこう!`, romaji: `ashita ikou`, meaning: `Tara bukas!` },
    ],
    remember: `ましょう = tayo na. ましょうか = tutulong ba ako? / gawin ba natin?`,
    tip: `Ang ましょうか ay isang magalang na paraan ng pag-alok ng tulong, madalas gamitin sa trabaho.`,
    check: { q: `"Mag-lunch tayo":`, options: [`たべません`, `たべましょう`, `たべました`, `たべたい`], answer: 1 },
  },
  {
    id: 'n4-kara-node',
    title: 'から at ので: dahil',
    pattern: 'A から B / A ので B',
    summary: 'Sabihin ang dahilan.',
    body: [
      `Parehong "dahil" o "kaya". Ang から ay mas tuwiran at subhetibo: あついですから、まどを あけます (mainit, kaya bubuksan ko ang bintana).`,
      `Ang ので ay mas magalang at obhetibo, kaya mas gamit sa pagpapaliwanag: あめなので、いきません. Gamit ang な-adj at pangngalan, gawing なので.`,
      `Sa isang tanong na "bakit?", どうして at なぜ. Ang sagot ay nagtatapos sa から: あめが ふっているからです.`,
    ],
    examples: [
      { jp: `いそがしいですから、いけません。`, romaji: `isogashii desu kara, ikemasen`, meaning: `Busy ako kaya hindi ako makakapunta.` },
      { jp: `びょうきなので、がっこうを やすみます。`, romaji: `byouki na node, gakkou o yasumimasu`, meaning: `Dahil may sakit ako, liliban ako.` },
      { jp: `どうして おそいですか。 ― ねぼうしたからです。`, romaji: `doushite osoi desu ka. neboushita kara desu`, meaning: `Bakit ka huli? Dahil nagising ako nang tanghali.` },
    ],
    remember: `から = kaya (diretso). ので = dahil (banayad). Ang sagot sa どうして ay 〜からです.`,
    tip: `Sa paghingi ng paumanhin sa trabaho, gamitin ang ので: mas magalang ang dating.`,
    check: { q: `Alin ang mas magalang para sa paliwanag?`, options: [`から`, `ので`, `けど`, `が`], answer: 1 },
  },
  {
    id: 'n4-tara-to',
    title: '〜たら at 〜と: kung at kapag',
    pattern: 'V ta + ら / V-る + と',
    summary: 'Mga kondisyon sa Japanese.',
    body: [
      `〜たら ay "kapag" o "kung" para sa isang tiyak na sitwasyon. Ang ta-form + ら: おわったら、でんわします (kapag natapos, tatawag ako).`,
      `〜と ay "tuwing/kapag ... laging" para sa natural na resulta at mga batas: はるに なると、さくらが さきます (kapag tagsibol, namumulaklak ang sakura).`,
      `Ang たら ay napaka-flexible, kaya para sa nagsisimula, ito ang pinakaligtas gamitin.`,
    ],
    examples: [
      { jp: `あした あめが ふったら、いきません。`, romaji: `ashita ame ga futtara, ikimasen`, meaning: `Kapag umulan bukas, hindi ako pupunta.` },
      { jp: `この ボタンを おすと、ドアが あきます。`, romaji: `kono botan o osu to, doa ga akimasu`, meaning: `Kapag pinindot ang button, bubukas ang pinto.` },
      { jp: `じかんが あったら、てつだってください。`, romaji: `jikan ga attara, tetsudatte kudasai`, meaning: `Kung may oras ka, pakitulungan ako.` },
    ],
    remember: `たら = kapag/kung (flexible). と = awtomatikong resulta.`,
    tip: `Hindi puwedeng gamitin ang と kung ang kasunod ay utos o hiling. Gamitin ang たら doon.`,
    check: { q: `Alin ang natural na resulta?`, options: [`たら`, `と`, `から`, `ので`], answer: 1 },
  },
];
