import type { ConceptLesson } from './concepts';

export const n3Lessons: ConceptLesson[] = [
  {
    id: 'n3-passive',
    title: 'Passive: 〜られる',
    pattern: 'V (a-stem + れる / る→られる)',
    summary: 'Kapag ang paksa ang tumanggap ng kilos.',
    body: [
      `Sa passive, ang paksa ay tumatanggap ng kilos, hindi gumagawa. "Ako ay tinawag ng guro" = せんせいに よばれました. Ang gumawa ay may に.`,
      `Pagbuo: Group 1: u → a + れる (よぶ → よばれる). Group 2: る → られる (たべる → たべられる). する → される, くる → こられる.`,
      `Isang espesyal na gamit ang "adversative passive" (迷惑の受身): ang kilos ay nakakaabala sa paksa. あめに ふられました = "Naulanan ako" (literal: inulanan ako, nainis ako). Walang direktang katumbas sa English, pero mayroon sa Tagalog sa "naulanan".`,
    ],
    examples: [
      { jp: `せんせいに ほめられました。`, romaji: `sensei ni homeraremashita`, meaning: `Pinuri ako ng guro.` },
      { jp: `どろぼうに かばんを ぬすまれました。`, romaji: `dorobou ni kaban o nusumaremashita`, meaning: `Ninakawan ako ng bag ng magnanakaw.` },
      { jp: `この ほんは せかいじゅうで よまれています。`, romaji: `kono hon wa sekaijuu de yomarete imasu`, meaning: `Binabasa ang aklat na ito sa buong mundo.` },
    ],
    remember: `Passive: paksa = tumatanggap. Gumawa = に. Madalas may damdamin ng abala.`,
    tip: `Ang potential at passive ng Group 2 ay magkapareho (たべられる). Konteksto lang ang nagsasabi kung alin.`,
    check: { q: `Passive ng よぶ?`, options: [`よばれる`, `よべる`, `よませる`, `よぼう`], answer: 0 },
  },
  {
    id: 'n3-causative',
    title: 'Causative: 〜させる',
    pattern: 'V (a-stem + せる / る→させる)',
    summary: 'Pagpapagawa at pagpapayag.',
    body: [
      `Ang causative ay "pinagawa" o "pinayagan". ははは わたしを かいものに いかせました = Pinabili ako ng nanay sa tindahan.`,
      `Pagbuo: Group 1: u → a + せる (いく → いかせる). Group 2: る → させる (たべる → たべさせる). する → させる, くる → こさせる.`,
      `Ang taong pinagawa ay may を (kung hindi transitive ang pandiwa) o に (kung may object na ibang を). Mas banayad ang に: "binigyan ng pahintulot".`,
      `Causative-passive (させられる) ay "napilitang gawin": ピーマンを たべさせられた = napilitan akong kumain ng pimiento.`,
    ],
    examples: [
      { jp: `ははは こどもに やさいを たべさせました。`, romaji: `haha wa kodomo ni yasai o tabesasemashita`, meaning: `Pinakain ng nanay ang bata ng gulay.` },
      { jp: `ぶちょうは わたしを ざんぎょうさせました。`, romaji: `buchou wa watashi o zangyou sasemashita`, meaning: `Pinag-overtime ako ng manager.` },
      { jp: `いかせてください。`, romaji: `ikasete kudasai`, meaning: `Pakiusap, hayaan mo akong pumunta.` },
    ],
    remember: `〜せる = pinagawa / pinayagan. 〜させられる = napilitan.`,
    tip: `〜させてください ay napakagamit sa trabaho para humingi ng pahintulot. Halimbawa: かえらせていただきます.`,
    check: { q: `Causative ng たべる?`, options: [`たべられる`, `たべさせる`, `たべせる`, `たべよう`], answer: 1 },
  },
  {
    id: 'n3-you-ni',
    title: '〜ようになる・〜ように: pagbabago at layunin',
    pattern: 'V-る + ように なる / する',
    summary: 'Naging kaya mo na. Subukan mong gawin.',
    body: [
      `V-る + ように なる ay "naging ganito na" (pagbabago sa kakayahan o gawi). にほんごが はなせるように なりました = Nagawa ko nang magsalita ng Japanese.`,
      `V-ない + ように なる ay "hindi na ginagawa". たばこを すわないように なりました = Hindi na ako naninigarilyo.`,
      `〜ように する ay "sinisikap kong...", at 〜ように ay "para ..." (layunin) kapag ang kasunod na pangungusap ay kilos: わすれないように メモします = Magsusulat ako ng tala para hindi makalimutan.`,
    ],
    examples: [
      { jp: `まいにち うんどうするように しています。`, romaji: `mainichi undou suru you ni shite imasu`, meaning: `Sinisikap kong mag-ehersisyo araw-araw.` },
      { jp: `かんじが よめるように なりました。`, romaji: `kanji ga yomeru you ni narimashita`, meaning: `Nakakabasa na ako ng kanji.` },
      { jp: `ちこくしないように はやく おきます。`, romaji: `chikoku shinai you ni hayaku okimasu`, meaning: `Gigising ako nang maaga para hindi mahuli.` },
    ],
    remember: `ようになる = naging. ようにする = sinisikap. ように = para (layunin).`,
    tip: `Ang ように ay madalas sa potential at ない. Kung sinadya mong magpasya, mas natural ang ことにする.`,
    check: { q: `"Nakakabasa na ako ng kanji":`, options: [`よむことにする`, `よめるようになった`, `よまされた`, `よんでいる`], answer: 1 },
  },
  {
    id: 'n3-hazu-beki-wake',
    title: 'はず・べき・わけ: inaasahan, dapat, kaya pala',
    pattern: 'V-plain + はず / べき / わけ',
    summary: 'Tatlong salita para sa lohika at inaasahan.',
    body: [
      `〜はずだ ay "dapat ay" o "tiyak na" batay sa katwiran: かれは もう つくはずです = Dapat nakarating na siya.`,
      `〜べきだ ay "dapat" (obligasyon, moral): がくせいは べんきょうするべきです = Dapat mag-aral ang mga estudyante. Para sa する, ang するべき o すべき.`,
      `〜わけだ ay "kaya pala" (konklusyon batay sa paliwanag): ながく すんでいたから、じょうずなわけです = Matagal siyang nakatira, kaya pala magaling. 〜わけがない ay "imposible".`,
    ],
    examples: [
      { jp: `ミーティングは さんじからのはずです。`, romaji: `miitingu wa sanji kara no hazu desu`, meaning: `Dapat ay alas-3 magsisimula ang meeting.` },
      { jp: `ひとに めいわくを かけるべきではありません。`, romaji: `hito ni meiwaku o kakeru beki dewa arimasen`, meaning: `Hindi dapat manggulo ng iba.` },
      { jp: `あんなに たべて、ふとるわけです。`, romaji: `anna ni tabete, futoru wake desu`, meaning: `Ganyan kalakas kumain, kaya pala tumataba.` },
    ],
    remember: `はず = inaasahan. べき = moral na dapat. わけ = lohikal na konklusyon.`,
    tip: `Ang はず ay hindi para sa gusto mo o plano mo. Ito ay hula batay sa impormasyon.`,
    check: { q: `Alin ang "dapat" sa moral na paraan?`, options: [`はず`, `べき`, `わけ`, `ばかり`], answer: 1 },
  },
  {
    id: 'n3-koto-ni',
    title: 'ことにする・ことになる: pagpapasya at kinahinatnan',
    pattern: 'V-る + ことに する / なる',
    summary: 'Ako ang nagpasya. Napagpasyahan.',
    body: [
      `〜ことにする ay "nagpasya akong..." (ikaw ang nagpasya): まいあさ はしることにしました = Nagpasya akong tumakbo tuwing umaga.`,
      `〜ことになる ay "napagpasyahan na..." (ibang tao o sitwasyon ang nagpasya, o opisyal na): らいげつ にほんへ いくことになりました = Napagpasyahan na pupunta ako sa Japan sa susunod na buwan.`,
      `Madalas gamitin ang ことになりました sa trabaho para sa mga anunsyo, dahil banayad itong paraan ng pagsasabi ng balita na parang hindi ikaw ang nagpasya.`,
    ],
    examples: [
      { jp: `たばこを やめることに しました。`, romaji: `tabako o yameru koto ni shimashita`, meaning: `Nagpasya akong huminto sa paninigarilyo.` },
      { jp: `らいしゅうから あたらしい ぶしょに いくことに なりました。`, romaji: `raishuu kara atarashii busho ni iku koto ni narimashita`, meaning: `Mula sa susunod na linggo, ililipat ako sa bagong departamento.` },
      { jp: `けっこんすることに なりました。`, romaji: `kekkon suru koto ni narimashita`, meaning: `Ikakasal na kami.` },
    ],
    remember: `ことにする = ikaw ang nagpasya. ことになる = napagpasyahan (opisyal o hindi mo desisyon).`,
    tip: `Sa pag-anunsyo ng kasal o promosyon, ことになりました ang mas nakagawian. Mas mapagpakumbaba ang dating.`,
    check: { q: `"Nagpasya akong mag-aral ng Japanese":`, options: [`ならうことになった`, `ならうことにした`, `ならわされた`, `ならえる`], answer: 1 },
  },
  {
    id: 'n3-bakari',
    title: 'ばかり: puro at kakatapos lang',
    pattern: 'N + ばかり / V-ta + ばかり',
    summary: 'Dalawang kahulugan: palagi at kakatapos.',
    body: [
      `N + ばかり ay "puro lang" o "laging": マンガばかり よんでいます = Puro manga lang ang binabasa ko. Madalas may bahagyang reklamo.`,
      `V-ta + ばかり ay "kakatapos lang": いま かえったばかりです = Kababalik ko lang. Ito ay nagsasaad ng kaunting oras mula nang mangyari.`,
      `Huwag ihalo sa だけ (lamang). ばかり ay "sobra" o "puro", at だけ ay neutral "lang". Ang ばかり ay madalas may negatibong kulay.`,
    ],
    examples: [
      { jp: `ゲームばかり していて、べんきょうしません。`, romaji: `geemu bakari shite ite, benkyou shimasen`, meaning: `Puro laro lang, hindi nag-aaral.` },
      { jp: `ごはんを たべたばかりです。`, romaji: `gohan o tabeta bakari desu`, meaning: `Kakakain ko lang.` },
      { jp: `かれは ぐちばかり いいます。`, romaji: `kare wa guchi bakari iimasu`, meaning: `Puro reklamo lang ang sinasabi niya.` },
    ],
    remember: `N ばかり = puro. V-ta ばかり = kakatapos lang.`,
    tip: `Sa casual, ばっかり ang madalas mong maririnig. Pareho ang kahulugan.`,
    check: { q: `"Kakarating ko lang":`, options: [`ついたばかりです`, `つくばかりです`, `ついてばかりです`, `つきばかりです`], answer: 0 },
  },
];

export const n2Lessons: ConceptLesson[] = [
  {
    id: 'n2-wake-dewa-nai',
    title: '〜わけではない: hindi naman ibig sabihin',
    pattern: 'plain + わけではない',
    summary: 'Pagtatama ng maling akala.',
    body: [
      `〜わけではない ay "hindi naman ibig sabihin na..." Ginagamit para itama ang maling konklusyon o paliwanag. たべないわけではない = hindi naman sa hindi ako kumakain.`,
      `Madalas itong sumusunod sa isang pahayag na may pagtutol: おさけは すきですが、まいにち のむわけではありません = Gusto ko ang alak, pero hindi naman araw-araw akong umiinom.`,
      `Mas banayad ito kaysa sa direktang "hindi". Parang "Hindi naman sa ganun..." sa Tagalog, madalas bago ang paliwanag.`,
    ],
    examples: [
      { jp: `きらいなわけではありませんが、あまり たべません。`, romaji: `kirai na wake dewa arimasen ga, amari tabemasen`, meaning: `Hindi naman sa ayaw ko, pero bihira akong kumain.` },
      { jp: `たかい ものが いいわけではない。`, romaji: `takai mono ga ii wake dewa nai`, meaning: `Hindi naman laging mas maganda ang mahal.` },
      { jp: `ひまなわけじゃないんです。`, romaji: `hima na wake janai n desu`, meaning: `Hindi naman sa libre ako.` },
    ],
    remember: `〜わけではない = hindi naman ibig sabihin. Itinatama ang akala.`,
    tip: `Madalas itong ipinapares sa ただ (kaya lang) o けれど: itinatanggi mo ang unang akala, tapos ibibigay ang totoong dahilan.`,
    check: { q: `Ano ang gamit nito?`, options: [`Magtanong`, `Itama ang maling akala`, `Humiling`, `Mag-anyaya`], answer: 1 },
  },
  {
    id: 'n2-zaru-wo-enai',
    title: '〜ざるを得ない: wala nang magagawa kundi',
    pattern: 'V-nai stem + ざるを得ない',
    summary: 'Napipilitan, hindi maiiwasan.',
    body: [
      `〜ざるを得ない ay "wala akong magagawa kundi" o "napipilitan akong...". Pormal at madalas sa pagsulat o pormal na pananalita.`,
      `Pagbuo: ない-form ngunit palitan ang ない ng ざる. いかない → いかざる → いかざるを得ない. Espesyal ang する: せざるを得ない.`,
      `Ito ay nagsasaad ng kawalan ng pagpipilian dahil sa sitwasyon, hindi dahil ayaw mo.`,
    ],
    examples: [
      { jp: `あめなので、えんそくを ちゅうしせざるを得ない。`, romaji: `ame nanode, ensoku o chuushi sezaru o enai`, meaning: `Dahil umuulan, wala nang magagawa kundi kanselahin ang field trip.` },
      { jp: `ぶちょうの めいれいだから、したがわざるを得ません。`, romaji: `buchou no meirei dakara, shitagawazaru o emasen`, meaning: `Utos ng manager, kaya wala akong magagawa kundi sumunod.` },
      { jp: `じこの ために ちこくせざるを得なかった。`, romaji: `jiko no tame ni chikoku sezaru o enakatta`, meaning: `Dahil sa aksidente, hindi maiwasang mahuli.` },
    ],
    remember: `ない → ざる + を得ない. する → せざる. = napipilitan.`,
    tip: `Sa casual, ginagamit ang しかない (gawin na lang). ざるを得ない ay mas matigas at pormal.`,
    check: { q: `Ang する ay nagiging...`, options: [`しざる`, `せざる`, `すざる`, `さざる`], answer: 1 },
  },
  {
    id: 'n2-nimo-kakawarazu',
    title: '〜にもかかわらず: sa kabila ng',
    pattern: 'N / plain + にもかかわらず',
    summary: 'Kahit na, sa kabila ng.',
    body: [
      `〜にもかかわらず ay "sa kabila ng" o "kahit na". Pormal, madalas sa balita at ulat. あめにもかかわらず、たくさんの ひとが あつまりました = Sa kabila ng ulan, maraming tao ang nagtipon.`,
      `Puwede itong gamitin sa pandiwa at adjective: さむいにもかかわらず, ねつが あるにもかかわらず. Para sa pangngalan at na-adj, tuwiran (だ ay tinatanggal o な ay ginagamit).`,
      `Katulad ng のに, pero mas pormal at hindi nagpapahayag ng reklamo o sama ng loob, kaya mas neutral.`,
    ],
    examples: [
      { jp: `びょうきにもかかわらず、かれは しごとに いった。`, romaji: `byouki ni mo kakawarazu, kare wa shigoto ni itta`, meaning: `Sa kabila ng sakit, pumasok siya sa trabaho.` },
      { jp: `たかいにもかかわらず、よく うれている。`, romaji: `takai ni mo kakawarazu, yoku utte iru`, meaning: `Kahit mahal, mabenta.` },
      { jp: `ねんれいにもかかわらず、げんきです。`, romaji: `nenrei ni mo kakawarazu, genki desu`, meaning: `Sa kabila ng edad, malakas pa rin.` },
    ],
    remember: `〜にもかかわらず = sa kabila ng. Pormal.`,
    tip: `Sa pang-araw-araw na usapan, gamitin ang のに o けど. Itong anyo ay para sa pagsulat at pormal na pananalita.`,
    check: { q: `Alin ang pinakamalapit sa kahulugan?`, options: [`dahil sa`, `sa kabila ng`, `bago`, `pagkatapos`], answer: 1 },
  },
  {
    id: 'n2-ni-taishite',
    title: '〜に対して: tungo sa, kontra sa, kumpara sa',
    pattern: 'N + に対して',
    summary: 'Sa direksyon ng, o sa kabaligtaran ng.',
    body: [
      `〜に対して (nitaishite) ay may tatlong gamit. (1) "Tungo sa" isang tao o bagay: おきゃくさまに たいして ていねいです (magalang sa mga customer).`,
      `(2) "Kumpara sa": あにが おとなしいのに たいして、おとうとは にぎやかです = Habang tahimik ang kuya, madaldal naman ang bunso.`,
      `(3) "Laban sa": さんせい に たいして はんたい = taliwas sa pagsang-ayon. Ang katulad na parirala ay 〜について (tungkol sa), kaya huwag silang paghalu-haluin.`,
    ],
    examples: [
      { jp: `せんせいに たいして しつれいな ことを いった。`, romaji: `sensei ni taishite shitsurei na koto o itta`, meaning: `Nagsabi siya ng bastos na bagay sa guro.` },
      { jp: `ちちは きびしいのに たいして、ははは やさしい。`, romaji: `chichi wa kibishii no ni taishite, haha wa yasashii`, meaning: `Mahigpit ang tatay, samantalang mabait ang nanay.` },
      { jp: `このけいかくに たいして はんたいです。`, romaji: `kono keikaku ni taishite hantai desu`, meaning: `Tutol ako sa planong ito.` },
    ],
    remember: `に対して = tungo sa / laban sa / kumpara sa. に ついて = tungkol sa.`,
    tip: `Isipin: に対して ay may "direksyon" o "kabaligtaran". に ついて ay tungkol lang sa paksa.`,
    check: { q: `Ang 〜に対して ay maaaring mangahulugan ng:`, options: [`tungkol sa lang`, `tungo sa o laban sa`, `bago`, `dahil sa`], answer: 1 },
  },
  {
    id: 'n2-monono',
    title: '〜ものの: kahit na, pero',
    pattern: 'plain + ものの',
    summary: 'Totoo ang una, pero hindi ganoon ang resulta.',
    body: [
      `〜ものの ay "kahit na" o "totoo man na... pero". Pormal. Ang unang bahagi ay katotohanan, ang ikalawa ay hindi inaasahang resulta.`,
      `かったものの、いちども つかっていない = Binili ko man, hindi ko pa nagamit kahit minsan. Ang pandiwa ay plain form (hindi ます).`,
      `Magkapareho sa 〜けれども, pero mas pormal at madalas sa pagsulat. Ang ikalawang bahagi ay madalas may pag-aatubili o pagsisisi.`,
    ],
    examples: [
      { jp: `やくそくは したものの、いきたくない。`, romaji: `yakusoku wa shita mono no, ikitakunai`, meaning: `Nangako man ako, ayoko nang pumunta.` },
      { jp: `しけんに ごうかくしたものの、しんぱいです。`, romaji: `shiken ni goukaku shita mono no, shinpai desu`, meaning: `Pumasa man ako sa exam, nag-aalala pa rin.` },
      { jp: `ざっしを かったものの、よむ じかんが ない。`, romaji: `zasshi o katta mono no, yomu jikan ga nai`, meaning: `Bumili ako ng magasin, pero wala akong oras para basahin.` },
    ],
    remember: `〜ものの = kahit na (pormal). Una: totoo. Ikalawa: salungat.`,
    tip: `Gamitin ang plain form lang bago ang ものの. Hindi puwede ang ます.`,
    check: { q: `Anong anyo ang kailangan bago ang ものの?`, options: [`ます-form`, `plain form`, `て-form`, `たい-form`], answer: 1 },
  },
];

export const n1Lessons: ConceptLesson[] = [
  {
    id: 'n1-zu-ni-wa-irarenai',
    title: '〜ずにはいられない: hindi mapigilan',
    pattern: 'V-nai stem + ずにはいられない',
    summary: 'Hindi mapigilang gumawa.',
    body: [
      `〜ずにはいられない ay "hindi ko mapigilang..." Nagpapahayag ng damdaming napakalakas, kaya napipilitan ang katawan na kumilos.`,
      `Pagbuo: Kunin ang ない-form at palitan ang ない ng ず: かう → かわない → かわず → かわずにはいられない. Espesyal ang する: せずにはいられない.`,
      `Kapareho ng 〜ないではいられない, pero mas pormal at literary. Madalas sa pagsulat ng emosyon: なかずにはいられなかった = hindi ko napigilang umiyak.`,
    ],
    examples: [
      { jp: `そのえいがを みて、なかずにはいられなかった。`, romaji: `sono eiga o mite, nakazu ni wa irarenakatta`, meaning: `Pagkapanood ko ng pelikulang iyon, hindi ko napigilang umiyak.` },
      { jp: `あまいものを みると、たべずにはいられない。`, romaji: `amai mono o miru to, tabezu ni wa irarenai`, meaning: `Kapag nakakakita ako ng matamis, hindi ko mapigilang kumain.` },
      { jp: `しんじつを きいて、おどろかずには いられなかった。`, romaji: `shinjitsu o kiite, odorokazu ni wa irarenakatta`, meaning: `Nang marinig ang katotohanan, hindi mapigilang magulat.` },
    ],
    remember: `ず + には + いられない = hindi mapigilan. する → せず.`,
    tip: `Ang paksa ay madalas ang nagsasalita mismo. Para sa ibang tao, gamitin ang "mukhang" (〜ようだ).`,
    check: { q: `Ano ang する sa pattern na ito?`, options: [`しずに`, `せずに`, `すずに`, `さずに`], answer: 1 },
  },
  {
    id: 'n1-narade-wa',
    title: '〜ならでは: natatangi sa',
    pattern: 'N + ならでは',
    summary: 'Ang kakaiba sa ganitong lugar o tao lamang.',
    body: [
      `〜ならでは ay "natatangi sa" o "tanging ... lamang ang makagagawa". Papuri ito, kaya ginagamit sa advertisement at review.`,
      `Madalas itong lumalabas sa mga pariralang gaya ng 京都ならではの たいけん (karanasang natatangi sa Kyoto) o プロならではの ぎじゅつ (teknik na tanging propesyonal ang may).`,
      `Ang istruktura: N + ならではの + N o N + ならではだ. Hindi ito ginagamit para sa negatibo, laging nagpapahayag ng paghanga.`,
    ],
    examples: [
      { jp: `きょうとならではの ふうけいを たのしむ。`, romaji: `kyouto narade wa no fuukei o tanoshimu`, meaning: `Tinatamasa ang tanawing natatangi sa Kyoto.` },
      { jp: `この あじは ははならではです。`, romaji: `kono aji wa haha narade wa desu`, meaning: `Ang lasa na ito ay natatangi sa nanay ko.` },
      { jp: `ベテランならではの はんだんだ。`, romaji: `beteran narade wa no handan da`, meaning: `Paghatol na tanging beterano ang may kakayahan.` },
    ],
    remember: `N + ならではの + N = "ang ___ na natatangi sa N". Papuri lagi.`,
    tip: `Hindi ito para sa pangungutya. Kung ang gusto mo ay "tipikal" (negatibo man), iba ang gamitin: らしい o ありがち.`,
    check: { q: `Anong damdamin ang dala nito?`, options: [`Pangungutya`, `Paghanga`, `Takot`, `Pagkabagot`], answer: 1 },
  },
  {
    id: 'n1-tomonaru-to',
    title: '〜ともなると: kapag umabot na sa antas na',
    pattern: 'N + ともなると / ともなれば',
    summary: 'Kapag ganoon na kalaki o kataas.',
    body: [
      `〜ともなると ay "kapag umabot na sa antas ng ___ ". Karaniwang mataas na antas, tungkulin, o edad: プロともなると = kapag propesyonal na.`,
      `Ang kasunod ay natural na resulta ng antas na iyon: こうこうせいともなると、よるおそくまで べんきょうする = Kapag high school na, nag-aaral na hanggang gabi.`,
      `Kaugnay ang 〜ともなれば. Magkapareho. Nagpapahiwatig ng "natural lang na ganoon".`,
    ],
    examples: [
      { jp: `ぶちょうともなると、せきにんも おもい。`, romaji: `buchou to mo naru to, sekinin mo omoi`, meaning: `Kapag manager na, mabigat na rin ang responsibilidad.` },
      { jp: `ねんまつともなると、どこも こんでいる。`, romaji: `nenmatsu to mo naru to, doko mo konde iru`, meaning: `Pagdating ng katapusan ng taon, siksikan kahit saan.` },
      { jp: `おやともなれば、こどもの ことが しんぱいだ。`, romaji: `oya to mo nareba, kodomo no koto ga shinpai da`, meaning: `Kapag magulang ka na, nag-aalala ka na sa anak.` },
    ],
    remember: `〜ともなると = kapag umabot na sa ___, natural na ganito.`,
    tip: `Hindi ito nilalagyan ng pangungusap na utos o kahilingan sa dulo, dahil ito ay obserbasyon.`,
    check: { q: `Ano ang inilalarawan ng ともなると?`, options: [`Hiling`, `Natural na resulta ng antas`, `Pagkakamali`, `Plano`], answer: 1 },
  },
  {
    id: 'n1-yoginaku',
    title: '〜を余儀なくされる: mapipilitan',
    pattern: 'N + を余儀なくされる',
    summary: 'Napilitan dahil sa mga pangyayari.',
    body: [
      `〜を余儀なくされる (yogi naku sareru) ay "napilitan sa" o "walang ibang pagpipilian kundi". Dahil sa labas na puwersa, hindi sa sariling kagustuhan.`,
      `Madalas sa balita: かいしゃは てったいを よぎなくされた = Napilitang umatras ang kompanya. Ito ay passive, kaya ang paksa ay ang tumatanggap ng pagpilit.`,
      `Kaugnay ng 〜ざるを得ない, pero mas pormal at madalas sa negatibong sitwasyon tulad ng krisis.`,
    ],
    examples: [
      { jp: `たいふうで、いべんとは ちゅうしを よぎなくされた。`, romaji: `taifuu de, ibento wa chuushi o yogi naku sareta`, meaning: `Dahil sa bagyo, napilitang kanselahin ang event.` },
      { jp: `けいえいなんで、かいしゃは しゅくしょうを よぎなくされた。`, romaji: `keiei nan de, kaisha wa shukushou o yogi naku sareta`, meaning: `Dahil sa kahirapan sa pamamahala, napilitan ang kompanya na mag-downsize.` },
      { jp: `かれは たいしょくを よぎなくされた。`, romaji: `kare wa taishoku o yogi naku sareta`, meaning: `Napilitan siyang magbitiw.` },
    ],
    remember: `N を余儀なくされる = napilitan ng sitwasyon. Pormal, madalas sa balita.`,
    tip: `Sa pagbabasa ng balita sa N1, madalas mo itong makikita. Kabisaduhin bilang isang buong parirala.`,
    check: { q: `Saan madalas ginagamit ito?`, options: [`Biruan`, `Balita at ulat`, `Text`, `Awit`], answer: 1 },
  },
  {
    id: 'n1-kirai-ga-aru',
    title: '〜きらいがある: may hilig na',
    pattern: 'V-plain / N の + きらいがある',
    summary: 'May tendensiyang hindi maganda.',
    body: [
      `〜きらいがある ay "may hilig na (negatibo)". Ang きらい dito ay hindi "ayaw" kundi "hilig" o "tendensiya". Palaging may negatibong kulay.`,
      `かれは ものごとを おおげさに かんがえる きらいが ある = Madalas niyang palakihin ang mga bagay. Ito ay puna sa ugali.`,
      `Huwag gamitin sa positibo: hindi mo sasabihing "may hilig siyang maging mabait" gamit ito. Para sa neutral, gamitin ang 〜がちだ o 〜やすい.`,
    ],
    examples: [
      { jp: `かれは ひとの はなしを きかない きらいが ある。`, romaji: `kare wa hito no hanashi o kikanai kirai ga aru`, meaning: `May ugali siyang hindi nakikinig sa iba.` },
      { jp: `わたしには、かんがえすぎる きらいが あります。`, romaji: `watashi ni wa, kangaesugiru kirai ga arimasu`, meaning: `May hilig akong mag-isip nang sobra.` },
      { jp: `この かいしゃには、ふるい やりかたに こだわる きらいが ある。`, romaji: `kono kaisha ni wa, furui yarikata ni kodawaru kirai ga aru`, meaning: `May hilig ang kompanyang ito na kumapit sa lumang paraan.` },
    ],
    remember: `〜きらいがある = may negatibong hilig. Hindi "ayaw".`,
    tip: `Pareho ang baybay ng きらい (ayaw) at ng きらい (hilig), kaya ang konteksto ang magsasabi. Sa pattern na ito, laging puna ito.`,
    check: { q: `Anong kulay ng kahulugan ang taglay?`, options: [`Positibo`, `Negatibo`, `Neutral`, `Pagbati`], answer: 1 },
  },
];
